# Generated by Django 5.1.2 on 2024-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('sound_field', models.FileField(upload_to='sounds/')),
            ],
        ),
    ]
