# Generated by Django 5.1.2 on 2024-10-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0003_lettersound'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='word_audios/')),
            ],
        ),
    ]
