# Generated by Django 5.1.2 on 2024-10-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0004_wordaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordaudio',
            name='acceptable_characters',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
