# Generated by Django 5.1.2 on 2024-10-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0005_wordaudio_acceptable_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordaudio',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordaudio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='word_images/'),
        ),
    ]
