# Generated by Django 5.1.2 on 2024-10-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0006_wordaudio_definition_wordaudio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='word_video/')),
                ('hint', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
