# Generated by Django 5.1.2 on 2024-10-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0007_wordvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_set', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
