# Generated by Django 5.1.2 on 2024-10-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0008_lettervideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('image', models.ImageField(upload_to='letter_images/')),
            ],
        ),
    ]
