# Generated by Django 5.1.2 on 2024-10-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0010_merge_20241023_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordCharade',
        ),
    ]
