# Generated by Django 5.1.2 on 2024-10-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0012_wordcharade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcharade',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charades', to='hahuapp.wordvideo'),
        ),
        migrations.AlterField(
            model_name='wordcharade',
            name='recording',
            field=models.FileField(upload_to='recordings/'),
        ),
    ]
