# Generated by Django 5.1.2 on 2024-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0014_alter_wordcharade_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcharade',
            name='recording',
            field=models.FileField(upload_to='recordings/'),
        ),
    ]
