# Generated by Django 5.1.2 on 2024-10-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hahuapp', '0015_alter_wordcharade_recording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcharade',
            name='question',
        ),
        migrations.AddField(
            model_name='wordcharade',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordcharade',
            name='object_id',
            field=models.PositiveIntegerField(default=True),
            preserve_default=False,
        ),
    ]
