# Generated by Django 5.1.2 on 2024-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0018_wordcountdownrecording_delete_wordcountdownattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcountdownrecording',
            name='letter',
        ),
        migrations.AlterField(
            model_name='wordcountdownrecording',
            name='recording',
            field=models.FileField(upload_to='word_count_down_recordings/'),
        ),
    ]
