# Generated by Django 5.1.2 on 2024-10-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0019_remove_wordcountdownrecording_letter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordcountdownrecording',
            old_name='created_at',
            new_name='submission_date',
        ),
        migrations.RemoveField(
            model_name='wordcountdownrecording',
            name='recording',
        ),
        migrations.AddField(
            model_name='wordcountdownrecording',
            name='audio_file',
            field=models.FileField(default=True, upload_to='word_countdown_recordings/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordcountdownrecording',
            name='letter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='hahuapp.letterimage'),
            preserve_default=False,
        ),
    ]
