# Generated by Django 5.1.2 on 2024-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0020_rename_created_at_wordcountdownrecording_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersound',
            name='sound_field',
            field=models.FileField(upload_to='letters/'),
        ),
    ]
