# Generated by Django 5.1.2 on 2024-10-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0021_alter_lettersound_sound_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersound',
            name='sound_field',
            field=models.FileField(upload_to='letter_sound/'),
        ),
    ]
