# Generated by Django 5.1.2 on 2024-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0023_alter_lettersound_sound_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sentence_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
