# Generated by Django 5.1.2 on 2024-10-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0024_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='definition',
            new_name='correct_definition',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='image',
        ),
    ]
