# Generated by Django 5.1.2 on 2024-10-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0025_rename_definition_sentence_correct_definition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='correct_definition',
            new_name='definition',
        ),
    ]
