# Generated by Django 5.1.2 on 2024-10-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0026_rename_correct_definition_sentence_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('main_idea', models.CharField(max_length=255)),
                ('wrong_choices', models.JSONField()),
            ],
        ),
    ]
