# Generated by Django 5.1.2 on 2024-11-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0027_passage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bingo/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='bingo/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='bingo/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BingoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('correct_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answers', to='hahuapp.bingoitem')),
                ('options', models.ManyToManyField(related_name='option_in_questions', to='hahuapp.bingoitem')),
            ],
        ),
        migrations.CreateModel(
            name='LetterSoundSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_order', models.TextField()),
                ('sounds', models.ManyToManyField(to='hahuapp.lettersound')),
            ],
        ),
    ]
