# Generated by Django 5.1.2 on 2024-11-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0028_bingoitem_bingoquestion_lettersoundsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='descriptive_images/')),
                ('correct_word', models.CharField(max_length=50)),
            ],
        ),
    ]
