# Generated by Django 5.1.2 on 2024-11-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0029_descriptiveimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveSentenceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='descriptive_images/')),
                ('correct_sentence', models.TextField(help_text='The correct sentence that describes the image')),
            ],
        ),
    ]
