# Generated by Django 5.1.2 on 2024-11-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0030_descriptivesentencequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text="Write the sentence with blanks represented by '__'.")),
                ('correct_answer', models.CharField(help_text='Write the correct answer(s) for the blank(s), separated by commas if multiple.', max_length=255)),
            ],
        ),
    ]
