# Generated by Django 5.1.2 on 2024-11-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0031_fillintheblank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='The number (e.g. 1, 2, 3).')),
                ('word', models.CharField(help_text='The word representation of the number (e.g. one, two, three).', max_length=100)),
            ],
        ),
    ]
