# Generated by Django 5.1.2 on 2024-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0032_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='amharic_word',
            field=models.CharField(blank=True, help_text='The word representation of the number in Amharic (e.g. ፩, ፪, ፫).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='word',
            field=models.CharField(help_text='The word representation of the number in English (e.g. one, two, three).', max_length=100),
        ),
    ]
