# Generated by Django 5.1.2 on 2024-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0035_video_videoresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
