# Generated by Django 5.1.2 on 2024-11-16 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0036_remove_video_video_url_video_video_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=2, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WordAudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_file', models.FileField(upload_to='user_recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='hahuapp.wordaudio')),
            ],
        ),
    ]
