# Generated by Django 5.1.2 on 2024-11-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0038_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/voice_recordings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
