# Generated by Django 5.1.2 on 2024-11-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0039_voicerecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmharicEnglishMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amharic_sentence', models.CharField(max_length=255)),
                ('english_sentence', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AmharicLetterFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('family', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LetterFillIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_word', models.CharField(max_length=100)),
                ('display_word', models.CharField(max_length=100)),
                ('correct_letter', models.CharField(max_length=1)),
                ('choices', models.JSONField()),
                ('meaning', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NumberToWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('amharic_number', models.CharField(help_text='put the equivalent amharic number e.g, ፩, ፯ ...', max_length=20)),
                ('number_name', models.CharField(help_text='insert the number in words', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_paragraph', models.TextField()),
                ('correct_order', models.JSONField()),
                ('sentences', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SentencePunctuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The sentence to display without punctuation')),
                ('correct_text', models.TextField(help_text='The correctly punctuated sentence')),
                ('choices', models.CharField(help_text='Comma-separated punctuation choices (e.g., .,!,?,;,:)', max_length=100)),
                ('correct_answer', models.CharField(help_text='The correct punctuation mark for this sentence', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('correct_word', models.CharField(max_length=100)),
                ('hint', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='story_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='AmharicLetterAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('audio_file', models.FileField(upload_to='amharic_audio/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='hahuapp.amharicletterfamily')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('audio_file', models.FileField(upload_to='story_audios/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='story_videos/')),
                ('text_content', models.TextField(blank=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='hahuapp.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hahuapp.storypart')),
            ],
        ),
    ]
