# Generated by Django 5.1.2 on 2024-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0041_userprofile_aura_points_userprofile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_bonus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
