# Generated by Django 5.1.2 on 2024-11-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahuapp', '0042_userprofile_last_login_bonus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='hahuapp.userprofile'),
        ),
    ]
